---
title: "Функции для рассчета коэффициента корреляции"
author: 'Александра Долгих'
date: "01 11 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Функция для рассчета коэффициента корреляции Пирсона

```{r pearson}
pearson_coef <- function(x){
  first <- x[,1]
  second <- x[,2]
  f_mean <- first - mean(first)
  s_mean <- second - mean(second)
  res <- sum(f_mean*s_mean)/sqrt(sum(f_mean**2)*sum(s_mean**2))
  print(res)
}
```

## Функция для рассчета коэффициента корреляции Спирмена


```{r spearman}
spearmen_coef <- function(x){
  first<-rank(x[,1])
  second<-rank(x[,2])
  f_mean <- first - mean(first)
  s_mean <- second - mean(second)
  res <- sum(f_mean*s_mean)/sqrt(sum(f_mean**2)*sum(s_mean**2))
  print(res)
}
```

### Создадим два тестовых dataframe
Первый на основе данных mtcars
data(mtcars)
Второй с повторяющимися значениями
```{r test}
for_t <- mtcars[3:4]
a <- c(1,1,1,2,3)
b <- a
for_t1 <- data.frame(a,b)
```
Протестируем наши функции и пакетные для сравнения
```{r test2}
spearmen_coef(for_t)
spearmen_coef(for_t1)
cor.test(for_t[,1],for_t[,2], method = "spearman")
cor.test(for_t1[,1],for_t1[,2], method = "spearman")

pearson_coef(for_t)
pearson_coef(for_t1)
cor.test(for_t[,1],for_t[,2])
cor.test(for_t1[,1],for_t1[,2])


```

